Update asan.yml

diff --git a/.github/workflows/asan.yml b/.github/workflows/asan.yml
--- a/.github/workflows/asan.yml
+++ b/.github/workflows/asan.yml
@@ -25,7 +25,7 @@ jobs:
       - name: Install dependencies for project (macOS)
         if: runner.os == 'macOS'
         run: |
-          brew update && brew install ninja meson llvm
+          brew update && brew install ninja meson llvm coreutils
         
       - name: Build repository 
         run: | 
@@ -36,7 +36,8 @@ jobs:
         if: runner.os == 'Linux'
         run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
       
-      - name: Run Google Address Sanitizer
+      - name: Run Google Address Sanitizer (Linux)
+        if: runner.os == 'Linux'
         run: |
           #!/bin/bash
 
@@ -53,6 +54,42 @@ jobs:
                   clang -I "$include_dirs" -fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g "$file" -o ./compiled.out > compilation.log 2>&1
                     if [ $? -eq 0 ]; then
                         timeout $TIMEOUT_DURATION ./compiled.out
+                        exit_status=$?
+                          if [ $exit_status -ne 0 ]; then
+                              ((successful_compilations += 1))
+                              cat compilation.log
+                              echo "--------------------------------------------------"
+                          else
+                              ((failed_compilations += 1))
+                          fi
+                    else
+                        ((failed_compilations += 1))
+                    fi
+                    rm -f ./compiled.out
+              fi
+          done
+
+          echo "Address Sanitizer Failures: $failed_compilations"
+          echo "Address Sanitizer Successes: $successful_compilations"
+
+      - name: Run Google Address Sanitizer (macOS)
+        if: runner.os == 'macOS'
+        run: |
+          #!/bin/bash
+
+          set +e 
+          
+          files=$(find . -type f)
+          failed_compilations=0
+          successful_compilations=0
+          TIMEOUT_DURATION=60
+
+          for file in $files; do
+              if [[ "$file" == *.c || "$file" == *.cpp ]]; then
+                  include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
+                  clang -I "$include_dirs" -fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g "$file" -o ./compiled.out > compilation.log 2>&1
+                    if [ $? -eq 0 ]; then
+                        gtimeout $TIMEOUT_DURATION ./compiled.out
                         exit_status=$?
                           if [ $exit_status -ne 0 ]; then
                               ((successful_compilations += 1))
